### ISSUE TITLE
This project needs a maintainer.

### ISSUE THREAD

**Issue by bashu** [praekelt/django-likes#18]
Hi,

This repository seems to lack maintenance, I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you

**Comment by ToferC** [comment]
+1

**Comment by ttyS15** [comment]
+1

**Comment by SillyInventor** [comment]
+1 someone definitely needs to maintain... it's broken with Django 1.8+ (module_name has been replaced by model_name), and I see there is already a pull request to fix this...

**Comment by Leprechaunz** [comment]
+1

**Comment by hedleyroos** [comment]
Hi. The 1.10 compatibility code is ready but we're waiting on a new release from https://github.com/jamesturk/django-secretballot. That had an issue which I fixed.

The code in the develop branch supports Django 1.10.

I'll ping secretballot's maintainer again.

**Comment by hedleyroos** [comment]
https://github.com/jamesturk/django-secretballot/issues/35

**Comment by jamesturk** [comment]
I did a 0.5.1 release followed quickly by an 0.6.0.  you probably want secretballot 0.6 to support Django 1.10, there were a few changes in the manager stuff keeping tests from passing, I think I have it working now though but please file an issue if there are any 1.10 issues

**Comment by bashu** [comment]
@hedleyroos sup?

**Comment by bashu** [comment]
@hedleyroos I am still ready to take over the project

**Comment by bashu** [comment]
@jamesturk thanks
