### ISSUE TITLE
Django 1.8 compatibility

### ISSUE THREAD

**Issue by RichardForshaw** [praekelt/django-likes#19]
In the templatetags, the following line fails:

`content_type': "-".join((obj._meta.app_label, obj._meta.module_name)),`

In Django 1.8, `Model._meta.module_name` has been replaced with `Model._meta.model_name`

https://docs.djangoproject.com/en/1.8/internals/deprecation/

**Comment by bashu** [comment]
to @RichardForshaw should be already fixed
