### ISSUE TITLE
didn't work

### ISSUE THREAD

**Issue by sky1048576** [praekelt/django-likes#24]
hello
why i cant install this
i did all of steps
i got this error:
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class secretballot.models.Vote doesn't declare an explicit a
pp_label and isn't in an application in INSTALLED_APPS.

**Comment by harunurkst** [comment]
add 
```
'secretballot',
  'likes',
```
to your INSTALLED_APPS

**Comment by bashu** [comment]
to @harunurkst thanks
